print("\n"+5*"#"+" KONVERSI DATA/OBJEK LAIN MENJADI DATA SET "+5*"#"+"\n")
dtString=input('masukan nama anda = ')
dt1=int(input('masukan tanggal lahir anda = '))
dt2=int(input('masukan bulan lahir anda = '))
dt3=int(input('masukan tahun lahir anda = '))
x=set(dtString)
y=set([dt1, dt2,dt3])
print(f"nama anda di konversi menjadi data set = {x}")
print(f"nama anda di konversi menjadi data set = {y}")