print("\n"+5*"#"+" MENAMBAHKAN BANYAK DATA KE DATA SET "+5*"#"+"\n")
st=set()
print(f"isi data set setelah ditambahkan data adalah = {st}")
range_set=int(input('masukan range data yang ingin di ubah = '))
dt1=input('masukan data pertama = ')
dt2=input('masukan data kedua = ')
dt3=input('masukan data ketiga = ') 
st.update(range(range_set))
st.update([dt1, dt2,dt3])
print(f"isi data set setelah ditambahkan data adalah || = {st}")